"""
Automated Containment & Firewall Blocklist Generator for LazySOC.
Generates instant, copy-paste containment rules and isolation scripts for:
- Windows Defender Firewall (PowerShell)
- Linux iptables, nftables, and ufw
- FortiGate FortiOS CLI
- Cisco ASA / IOS CLI
- Palo Alto Networks PAN-OS CLI
- MikroTik RouterOS
- EDR Hash Ban lists (CrowdStrike, SentinelOne, Defender)
"""

import datetime
from typing import List, Dict, Any, Set


def generate_containment_rules(iocs: List[Dict[str, Any]], custom_comment: str = "LazySOC Incident Containment") -> Dict[str, Any]:
    """
    Parses a list of IoC dictionaries and generates containment scripts for various platforms.
    Each IoC item can have 'indicator', 'type', 'verdict'.
    """
    now_str = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    # Filter malicious & suspicious items, or all if none marked
    target_items = [i for i in iocs if i.get("verdict", "").upper() in ("MALICIOUS", "SUSPICIOUS")]
    if not target_items:
        target_items = iocs

    ipv4_list: Set[str] = set()
    ipv6_list: Set[str] = set()
    domain_list: Set[str] = set()
    hash_list: Set[str] = set()

    for item in target_items:
        val = str(item.get("indicator", "")).strip().replace("[.]", ".").replace("hxxp://", "http://").replace("hxxps://", "https://")
        ioc_type = item.get("type", "").lower()

        if ioc_type in ("ipv4", "ip"):
            ipv4_list.add(val)
        elif ioc_type == "ipv6":
            ipv6_list.add(val)
        elif ioc_type in ("domain", "hostname", "url"):
            # Extract pure domain if it's a URL
            if "://" in val:
                val = val.split("://")[1].split("/")[0].split(":")[0]
            domain_list.add(val)
        elif ioc_type in ("md5", "sha1", "sha256", "hash"):
            hash_list.add(val)

    sorted_ips = sorted(list(ipv4_list) + list(ipv6_list))
    sorted_domains = sorted(list(domain_list))
    sorted_hashes = sorted(list(hash_list))

    total_iocs = len(sorted_ips) + len(sorted_domains) + len(sorted_hashes)

    # 1. Windows Defender Firewall (PowerShell)
    ps_lines = [
        f"# ==========================================================================",
        f"# LazySOC Windows Defender Firewall Containment Script",
        f"# Generated: {now_str} | Target IoCs: {total_iocs}",
        f"# Run this script in an Elevated Administrator PowerShell Console",
        f"# ==========================================================================\n",
    ]
    if sorted_ips:
        ps_lines.append(f"# Block Remote IP Addresses (Inbound & Outbound)")
        ps_lines.append(f"$MaliciousIPs = @(")
        for ip in sorted_ips:
            ps_lines.append(f'    "{ip}",')
        ps_lines.append(")")
        ps_lines.append("""
foreach ($ip in $MaliciousIPs) {
    $ruleNameIn = "LazySOC_Block_In_$ip"
    $ruleNameOut = "LazySOC_Block_Out_$ip"
    if (-not (Get-NetFirewallRule -DisplayName $ruleNameIn -ErrorAction SilentlyContinue)) {
        New-NetFirewallRule -DisplayName $ruleNameIn -Direction Inbound -Action Block -RemoteAddress $ip -Description "$custom_comment - Generated by LazySOC" | Out-Null
        Write-Host "[+] Created Inbound Block Rule for $ip" -ForegroundColor Green
    }
    if (-not (Get-NetFirewallRule -DisplayName $ruleNameOut -ErrorAction SilentlyContinue)) {
        New-NetFirewallRule -DisplayName $ruleNameOut -Direction Outbound -Action Block -RemoteAddress $ip -Description "$custom_comment - Generated by LazySOC" | Out-Null
        Write-Host "[+] Created Outbound Block Rule for $ip" -ForegroundColor Green
    }
}""")
    if sorted_domains:
        ps_lines.append(f"\n# Hostfile Domain Sinkhole Routing (127.0.0.1)")
        ps_lines.append(f"$hostsPath = '$env:SystemRoot\\System32\\drivers\\etc\\hosts'")
        for d in sorted_domains:
            ps_lines.append(f'Add-Content -Path $hostsPath -Value "127.0.0.1 {d} # {custom_comment}"')
    if not sorted_ips and not sorted_domains:
        ps_lines.append("# No IP or domain indicators available for network firewall rules.")

    # 2. Linux iptables & UFW
    linux_lines = [
        f"# ==========================================================================",
        f"# LazySOC Linux Netfilter (iptables & ufw) Containment Rules",
        f"# Generated: {now_str}",
        f"# Apply using root privileges (sudo bash)",
        f"# ==========================================================================\n",
    ]
    if sorted_ips:
        linux_lines.append("# --- iptables Drop Commands ---")
        for ip in sorted_ips:
            linux_lines.append(f"iptables -I INPUT -s {ip} -j DROP -m comment --comment \"{custom_comment}\"")
            linux_lines.append(f"iptables -I OUTPUT -d {ip} -j DROP -m comment --comment \"{custom_comment}\"")
        linux_lines.append("\n# --- Ubuntu UFW Drop Commands ---")
        for ip in sorted_ips:
            linux_lines.append(f"ufw insert 1 deny from {ip} to any comment '{custom_comment}'")
            linux_lines.append(f"ufw insert 1 deny out to {ip} comment '{custom_comment}'")
    if sorted_domains:
        linux_lines.append("\n# --- /etc/hosts Domain Sinkhole ---")
        for d in sorted_domains:
            linux_lines.append(f"echo '127.0.0.1 {d} # {custom_comment}' >> /etc/hosts")

    # 3. FortiGate (FortiOS CLI)
    fg_lines = [
        f"# ==========================================================================",
        f"# FortiGate (FortiOS) Address Object & Quarantine Group",
        f"# Generated: {now_str}",
        f"# ==========================================================================",
        "config firewall address",
    ]
    fg_members = []
    for ip in sorted_ips:
        obj_name = f"LazySOC_{ip.replace(':', '_')}"
        fg_members.append(obj_name)
        fg_lines.extend([
            f'    edit "{obj_name}"',
            f'        set subnet {ip} 255.255.255.255' if "." in ip else f'        set ip6 {ip}/128',
            f'        set comment "{custom_comment}"',
            "    next",
        ])
    for d in sorted_domains:
        clean_d = d.replace(".", "_")
        obj_name = f"LazySOC_FQDN_{clean_d}"
        fg_members.append(obj_name)
        fg_lines.extend([
            f'    edit "{obj_name}"',
            f'        set type fqdn',
            f'        set fqdn "{d}"',
            f'        set comment "{custom_comment}"',
            "    next",
        ])
    fg_lines.append("end")

    if fg_members:
        fg_str = " ".join([f'"{m}"' for m in fg_members[:40]])
        fg_lines.extend([
            "\nconfig firewall addrgrp",
            '    edit "LazySOC_QUARANTINE_GROUP"',
            f'        set comment "{custom_comment}"',
            f'        set member {fg_str}',
            "    next",
            "end",
            "\n# Attach 'LazySOC_QUARANTINE_GROUP' to top DENY policy in Firewall Policy table.",
        ])

    # 4. Cisco ASA / Firepower
    cisco_lines = [
        f"! ==========================================================================",
        f"! Cisco ASA / IOS Access-Control List (ACL) Drop Rules",
        f"! Generated: {now_str}",
        f"! ==========================================================================",
    ]
    for ip in sorted_ips:
        cisco_lines.append(f"access-list LAZYSOC_QUARANTINE line 1 extended deny ip host {ip} any")
        cisco_lines.append(f"access-list LAZYSOC_QUARANTINE line 1 extended deny ip any host {ip}")
    for d in sorted_domains:
        cisco_lines.append(f"! Domain FQDN block: {d}")
        cisco_lines.append(f"name {d} DOMAIN_{d.replace('.', '_')}")

    # 5. Palo Alto Networks (PAN-OS CLI)
    pa_lines = [
        f"# ==========================================================================",
        f"# Palo Alto Networks PAN-OS CLI Address Objects",
        f"# Generated: {now_str}",
        f"# ==========================================================================",
    ]
    pa_members = []
    for ip in sorted_ips:
        obj_name = f"LazySOC_{ip.replace(':', '_')}"
        pa_members.append(obj_name)
        pa_lines.append(f'set address "{obj_name}" ip-netmask {ip}/32 description "{custom_comment}"')
    for d in sorted_domains:
        obj_name = f"LazySOC_FQDN_{d.replace('.', '_')}"
        pa_members.append(obj_name)
        pa_lines.append(f'set address "{obj_name}" fqdn {d} description "{custom_comment}"')
    if pa_members:
        pa_str = " ".join([f'"{m}"' for m in pa_members[:40]])
        pa_lines.append(f'\nset address-group "LazySOC_BLOCKLIST" static [ {pa_str} ]')

    # 6. MikroTik RouterOS
    mikrotik_lines = [
        f"# ==========================================================================",
        f"# MikroTik RouterOS Firewall Address-List",
        f"# Generated: {now_str}",
        f"# ==========================================================================",
    ]
    for ip in sorted_ips:
        mikrotik_lines.append(f'/ip firewall address-list add list=LAZYSOC_ISOLATION address={ip} comment="{custom_comment}"')
    for d in sorted_domains:
        mikrotik_lines.append(f'/ip firewall address-list add list=LAZYSOC_ISOLATION address={d} comment="{custom_comment}"')
    if sorted_ips or sorted_domains:
        mikrotik_lines.append(
            '/ip firewall filter add chain=forward action=drop src-address-list=LAZYSOC_ISOLATION place-before=0 comment="LazySOC Drop Inbound"'
        )
        mikrotik_lines.append(
            '/ip firewall filter add chain=forward action=drop dst-address-list=LAZYSOC_ISOLATION place-before=0 comment="LazySOC Drop Outbound"'
        )

    # 7. EDR Hash Ban Format
    edr_lines = [
        f"# ==========================================================================",
        f"# EDR File Hash Ban List (CrowdStrike Falcon / SentinelOne / Microsoft Defender)",
        f"# Generated: {now_str} | Total Hashes: {len(sorted_hashes)}",
        f"# ==========================================================================\n",
        "# --- CrowdStrike Falcon Custom IOC Format (CSV) ---",
        "Type,Value,Action,Severity,Description",
    ]
    for h in sorted_hashes:
        h_type = "sha256" if len(h) == 64 else ("sha1" if len(h) == 40 else "md5")
        edr_lines.append(f"{h_type.upper()},{h},block,critical,{custom_comment}")

    edr_lines.append("\n# --- SentinelOne / Raw Hash List ---")
    for h in sorted_hashes:
        edr_lines.append(h)

    return {
        "total_targets": total_iocs,
        "counts": {
            "ips": len(sorted_ips),
            "domains": len(sorted_domains),
            "hashes": len(sorted_hashes),
        },
        "scripts": {
            "powershell": "\n".join(ps_lines),
            "linux": "\n".join(linux_lines),
            "fortigate": "\n".join(fg_lines),
            "cisco": "\n".join(cisco_lines),
            "paloalto": "\n".join(pa_lines),
            "mikrotik": "\n".join(mikrotik_lines),
            "edr": "\n".join(edr_lines),
        },
    }
